import Link from 'next/link';
import type { Metadata } from 'next';
import { SectionHead, CtaBand } from '@/components/Studio';
import { STAGES } from '@/content/process';
import { PACKAGES, eur } from '@/content/packages';

export const metadata: Metadata = {
  title: 'How a project runs',
  description:
    'Register, choose a package, pay a 10% deposit, upload your concept, receive a completion date, pay 40% to start production, settle the final 50% at 75–80% progress, and take handover at 100%.',
  alternates: { canonical: '/process' },
};

const STEPS = [
  {
    n: '01',
    title: 'Register and choose your package',
    body: 'Create an account in the client portal and pick the package that matches what you are building. Add any add-on services, a setup plan and a care plan if you want them. The portal shows the indicative quote and the exact milestone amounts before you commit to anything.',
    detail: ['Free to register', 'Ten packages to choose from', 'Add-ons optional and priced individually', 'Nothing is charged at this step'],
  },
  {
    n: '02',
    title: 'Pay the 10% booking deposit',
    body: 'A 10% deposit reserves your slot in the production queue and opens the concept upload. It is the minimum — you may pay more if you prefer, and the extra simply counts against the next milestone. Pay in USDT on TRC20, ERC20 or BEP20, or in EUR via PayPal.',
    detail: ['Minimum 10% of the contract value', 'USDT or PayPal', 'Confirmed within one business day', 'Deducted from the total, never an extra fee'],
  },
  {
    n: '03',
    title: 'Upload your concept',
    body: 'Once the deposit clears, the upload panel unlocks. Send whatever describes the website you want: a brief, a deck, screenshots of sites you like, your logo and brand files, copy, product data, wireframes. You can add more at any point during the build.',
    detail: ['PDF, images, office documents, design files, ZIP', 'Up to 25 MB per file', 'Written notes as well as files', 'Private — visible only to you and the delivery team'],
  },
  {
    n: '04',
    title: 'Your completion date appears',
    body: 'The moment your concept lands, the portal fixes a delivery estimate from the package timeline and publishes it on your project page. We review scope against what you uploaded and confirm the final contract value; the milestone amounts recalculate from that figure automatically.',
    detail: ['Estimate visible from day one', 'Scope review within one business day', 'Final contract value confirmed in writing', 'Milestones recalculated automatically'],
  },
  {
    n: '05',
    title: 'Pay 40% — production begins',
    body: 'The second payment brings you to 50% of the contract and starts the build. Design first, then implementation, with the progress bar and activity log updated as real work lands. Progress under this payment runs up to 80%.',
    detail: ['Cumulative 50% paid', 'Design, then build', 'Live progress percentage', 'Dated activity log on every change'],
  },
  {
    n: '06',
    title: 'Settle the final 50% at 75–80%',
    body: 'When the build reaches 75%, the settlement invoice is raised automatically and you get a working preview to check. Progress is capped at 80% until it clears — you never pay for work you cannot see, and we never hand over work that has not been paid for.',
    detail: ['Triggered at 75% progress', 'Preview environment to review', 'Hard cap at 80% until settled', 'Invoice generated by the portal'],
  },
  {
    n: '07',
    title: 'Handover at 100%',
    body: 'The last 20% is deployment, content loading, testing, performance and SEO passes, and training. At 100% you receive the source code, the design files, the admin accounts and the infrastructure — plus a walkthrough so your team can run it.',
    detail: ['Source code and design files transferred', 'Admin and infrastructure accounts handed over', 'Live deployment and final QA', 'Training session and documentation'],
  },
];

export default function ProcessPage() {
  const example = PACKAGES.find((p) => p.slug === 'company-profile')!;
  const contract = example.priceMin;

  return (
    <>
      <section className="relative overflow-hidden metal-wash text-ivory-50">
        <div className="mk-grid-bg absolute inset-0" />
        <div className="relative mx-auto max-w-6xl px-4 py-16">
          <span className="mk-chip border-white/25 text-ivory-100">How it works</span>
          <h1 className="mt-5 max-w-3xl font-serif text-4xl font-black leading-tight sm:text-5xl">
            You pay in three steps. <span className="accent-text">You can watch every one of them.</span>
          </h1>
          <p className="mt-5 max-w-2xl text-[15px] leading-relaxed text-ivory-100/80">
            Most studios ask for half up front and go quiet. We split the money across the life of the build and put the
            progress bar where you can see it — so the incentive to finish stays with us, and the risk never all sits
            with you.
          </p>
        </div>
      </section>

      {/* The money, in one picture */}
      <section className="mx-auto max-w-6xl px-4 py-14">
        <SectionHead eyebrow="The payment schedule" title="10% · 40% · 50%" lead="Three payments, tied to real events rather than to dates on a calendar." />
        <div className="mt-8 panel p-6 sm:p-8">
          <div className="flex h-12 w-full overflow-hidden rounded-lg text-xs font-black text-white">
            <div className="flex items-center justify-center bg-[#0a52bd]" style={{ width: '10%' }}>10%</div>
            <div className="flex items-center justify-center bg-[#0b6fe8]" style={{ width: '40%' }}>40%</div>
            <div className="flex items-center justify-center bg-[#2f9dff]" style={{ width: '50%' }}>50%</div>
          </div>
          <div className="mt-4 grid gap-5 sm:grid-cols-3">
            <div>
              <p className="font-serif text-lg font-black">Booking deposit</p>
              <p className="text-sm text-ink-800/70">Paid at order. Reserves the slot, opens the concept upload.</p>
            </div>
            <div>
              <p className="font-serif text-lg font-black">Production</p>
              <p className="text-sm text-ink-800/70">Paid once the scope is agreed. Starts the build; progress runs to 80%.</p>
            </div>
            <div>
              <p className="font-serif text-lg font-black">Settlement</p>
              <p className="text-sm text-ink-800/70">Paid at 75–80% progress, after you have seen it working. Releases handover.</p>
            </div>
          </div>

          <div className="mt-8 rounded-lg bg-ivory-100/70 p-5">
            <p className="text-xs font-black uppercase tracking-wider text-steel-500">Worked example — {example.name}</p>
            <table className="data-table mt-3">
              <tbody>
                <tr><td>Contract value (scope agreed)</td><td className="text-right font-bold">{eur(contract)}</td></tr>
                <tr><td>1. Booking deposit — 10%, at order</td><td className="text-right font-bold">{eur(Math.round(contract * 0.1))}</td></tr>
                <tr><td>2. Production — 40%, build starts</td><td className="text-right font-bold">{eur(Math.round(contract * 0.4))}</td></tr>
                <tr><td>3. Settlement — 50%, at 75–80% progress</td><td className="text-right font-bold">{eur(Math.round(contract * 0.5))}</td></tr>
                <tr><td className="font-bold">Total build cost</td><td className="text-right font-black">{eur(contract)}</td></tr>
              </tbody>
            </table>
            <p className="hint mt-3">
              Setup ({eur(149)}–{eur(399)} one-time) and a care plan (from {eur(99)}/month) are separate services, invoiced on
              their own. They are never bundled into the build price without you choosing them.
            </p>
          </div>
        </div>
      </section>

      {/* Steps */}
      <section className="mx-auto max-w-6xl px-4 py-10">
        <SectionHead eyebrow="Step by step" title="From registration to handover" />
        <div className="mt-10 space-y-6">
          {STEPS.map((s) => (
            <article key={s.n} className="panel grid gap-6 p-6 sm:grid-cols-[auto_1fr_260px] sm:items-start">
              <span className="font-serif text-4xl font-black accent-text">{s.n}</span>
              <div>
                <h3 className="font-serif text-xl font-black">{s.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-ink-800/75">{s.body}</p>
              </div>
              <ul className="space-y-1.5 rounded-lg bg-ivory-100/60 p-4 text-xs">
                {s.detail.map((d) => (
                  <li key={d} className="flex gap-2"><span className="tick">✓</span><span>{d}</span></li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      {/* Stage rail */}
      <section className="mx-auto max-w-6xl px-4 py-12">
        <div className="panel-dark p-8">
          <h2 className="font-serif text-2xl font-black">What your project page shows</h2>
          <p className="mt-2 max-w-2xl text-sm text-ivory-100/75">
            Every project in the portal carries the same seven-stage rail. Stages light up from facts on record — a
            confirmed payment, an uploaded file, a progress update — never by hand.
          </p>
          <ol className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {STAGES.map((s, i) => (
              <li key={s.key} className="rounded-lg border border-white/15 bg-white/5 p-4">
                <p className="text-[11px] font-black text-gold-300">STAGE {i + 1}</p>
                <p className="mt-1 text-sm font-bold">{s.name}</p>
                <p className="mt-1 text-xs text-ivory-100/65">{s.blurb}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Honest boundaries */}
      <section className="mx-auto max-w-6xl px-4 py-12">
        <SectionHead eyebrow="The small print, said plainly" title="What can move a date" lead="Timelines are estimates drawn from the package, and they hold when both sides keep moving. These are the things that genuinely shift them." />
        <div className="mt-8 grid gap-5 md:grid-cols-2">
          {[
            { t: 'Content arriving late', b: 'The single most common cause of delay. Copy, photography, product data and legal text sit on your side; the clock effectively pauses while we wait for them.' },
            { t: 'Scope added mid-build', b: 'New features are welcome, but they are quoted and scheduled as a change, not absorbed silently into the same date.' },
            { t: 'Third parties', b: 'Payment providers, banks, identity checks and API approvals move at their own pace. We start those early and tell you the moment one is blocking.' },
            { t: 'Review cycles', b: 'Each review round we wait on adds to the timeline. Two named decision-makers on your side is usually the difference between weeks and months.' },
          ].map((x) => (
            <div key={x.t} className="panel p-5">
              <h3 className="font-bold">{x.t}</h3>
              <p className="mt-2 text-sm leading-relaxed text-ink-800/70">{x.b}</p>
            </div>
          ))}
        </div>
        <p className="mt-6 text-sm text-ink-800/70">
          If a delay is ours, we say so on the activity log and we do not invoice a milestone we have not reached.{' '}
          <Link href="/terms" className="text-gold-500 underline">Full terms</Link>.
        </p>
      </section>

      <CtaBand
        title="Open a project and see it for yourself"
        lead="Registration is free. You will see the exact milestone amounts for your package before any payment is due."
      />
    </>
  );
}
